name: mannal-build

on:
    workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: generatingversionnumber
        id: generating-version-number
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          $VersionFileStr = Get-Content .\VERSION.txt
          $VersionNunber = ($VersionFileStr | ForEach-Object { $_[-1] }) -join '.'
          "VersionNunber=$VersionNunber" >> $env:GITHUB_OUTPUT

      - name: printversionnumber
        run: |
          Write-Output "the VersionNunber is ${{ steps.generating-version-number.outputs.VersionNunber }}"